db:
  connection_string: "host=localhost port=5433 user=postgres dbname=postgres options='-c search_path=public' password=12345 sslmode=disable"

minio:
  host: "192.168.181.153:9000"
  location: "us-east-1"
  accessKeyId: "minio"
  secretAccessKey: "minio124"
  bucketName: "stars"